micronaut:
  application:
    name: medication-administration-service
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - "http://localhost:3000"
            - "http://localhost:4200"
            - "http://localhost:5173"
            - "http://localhost:8080"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - "*"
          allow-credentials: true
          max-age: 3600
  http:
    client:
      read-timeout: 30s
      connect-timeout: 10s
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:please-change-this-to-a-real-secret-in-production}

datasources:
  default:
    # DynamoDB configuration would go here for production
    # Test environment will use in-memory implementations

logging:
  level:
    com.healthcare.medication: DEBUG
    org.springframework.security: INFO
    io.micronaut: INFO

healthcare:
  medication:
    audit:
      enabled: true
    compliance:
      hipaa-enabled: true
    safety:
      double-check-required: true